name: 'Check PR Issue Action'
description: 'Validates that PRs are linked to issues and optionally enforces assignee requirements'
author: 'arkid15r'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  skip_users:
    description: 'Comma-separated list of usernames to skip validation'
    required: false
    default: ''
  require_assignee:
    description: 'Whether to require issue assignee to match PR author'
    required: false
    default: 'false'
  close_pr_on_failure:
    description: 'Whether to close PR when validation fails (default: true)'
    required: false
    default: 'true'
  no_issue_message:
    description: 'Error message when PR has no linked issue'
    required: false
    default: 'This PR must be linked to an issue before it can be merged.'
  assignee_mismatch_message:
    description: 'Error message when assignee does not match PR author'
    required: false
    default: 'The linked issue must be assigned to the PR author before this PR can be merged.'
  github_token:
    description: 'GitHub token for API access'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
