name: Check PR Issue Action
description: Validates that PRs are linked to issues and optionally enforces assignee requirements
author: arkid15r
branding:
  icon: check-circle
  color: green

inputs:
  skip_users:
    description: Comma-separated list of usernames to skip validation
    required: false
    default: ''
  skip_users_file_path:
    description: Path to a file containing usernames to skip validation (one username per line)
    required: false
    default: ''
  check_issue_reference:
    description: Whether to allow PRs without a linked issue when the PR description contains a valid closing issue reference
    required: false
    default: 'false'
  require_assignee:
    description: Whether to require issue assignee to match PR author
    required: false
    default: 'false'
  close_pr_on_failure:
    description: 'Whether to close PR when validation fails (default: true)'
    required: false
    default: 'true'
  no_issue_message:
    description: 'Error message when PR has no linked issue'
    required: false
    default: This PR must be linked to an issue before it can be merged.
  no_assignee_message:
    description: 'Error message when assignee does not match PR author'
    required: false
    default: The linked issue must be assigned to the PR author before this PR can be merged.
  target_branches:
    description: Newline-separated list of target branches to validate against (repository default branch is automatically included)
    required: false
    default: ''
  invalid_branch_message:
    description: Error message when PR targets an invalid branch
    required: false
    default: 'This PR must target one of the allowed branches.'
  github_token:
    description: 'GitHub token for API access'
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/arkid15r/check-pr-issue-action:latest'
