name: Test Action

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-action:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Test action
      uses: arkid15r/check-pr-issue-action@test
      with:
        close_pr_on_failure: 'true'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        no_assignee_message: 'Test: The linked issue must be assigned to the PR author.'
        no_issue_message: 'Test: This PR must be linked to an issue.'
        require_assignee: 'true'
